#!/data/data/com.termux/files/usr/bin/env bash
#
# EXT
set -e

id="$(id -u)"
bsdtar --uid "${id}" --gid "${id}" \
  -x -f "${PREFIX}/tmp/tqs/cfg.tar" -C "${PREFIX%/*}"

chsh -s zsh
rm -rf "${PREFIX}/etc/termux"
echo > "${PREFIX}/etc/motd"
[[ ! -d "${PREFIX%/*}/home/storage" ]] && termux-setup-storage

echo
echo '- Keep this empty
  if you will not use SSH'
passwd

echo '- That is all. Close all sessions (CTRL + D)'
