#!/data/data/com.termux/files/usr/bin/env bash
#
# EXT
set -e

id="$(id -u)"
bsdtar --uid "${id}" --gid "${id}" \
  -x -f "${PREFIX}/tmp/tqs/cfg.tar" -C "${PREFIX%/*}"

chsh -s zsh
rm -rf "${PREFIX}/etc/termux"
echo > "${PREFIX}/etc/motd"
[[ ! -d "${HOME}/storage" ]] && termux-setup-storage
passwd

kill "${TERMUX_APP_PID}"
