#!/system/bin/env sh
#
# Setup pacman in termux
set -e

dir="${PREFIX}/../tqs"
tmp="${TMPDIR}/tqs"
url="https://github.com/nedorazrab0/tqs/releases/download/tqs/tqs.tar.lz4"

# Check failsafe
if [ -n "${TERMUX_MAIN_PACKAGE_FORMAT}" ]; then
  echo '! Not failsafe'
  echo '- Left edge swipe ==> "new session" (long-tap)'
  exit 1
fi

# Main
[ -d "${dir}" ] && rm -rf "${dir}"
mkdir -p "${dir}"

if [ "$(uname -m)" == 'aarch64' ]; then
  arch='aarch64'
else
  arch='arm'
fi

"${PREFIX}/bin/curl" -fLZ "https://github.com/termux-pacman/termux-packages/\
releases/latest/download/bootstrap-${arch}.zip" \
  -o "${PREFIX}/trp.zip"

unzip "${PREFIX}/trp.zip" -d "${dir}"
cd "${dir}"  # For symlinks
awk -F '←' \
  '{system("ln -sv '"'"'"$1"'"'"' '"'"'"$2"'"'"' &")}' \
  "${dir}/SYMLINKS.txt"
rm -f "${dir}/SYMLINKS.txt"
rm -rf "${PREFIX}"
cd ..
mv "${dir}" "${PREFIX}"

# EXT
export PATH="${PREFIX}/bin"

cat << 'EOF' > "${PREFIX}/etc/pacman.conf"
[options]
HoldPkg = pacman
Architecture = auto

Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 12

SigLevel = DatabaseRequired
LocalFileSigLevel = Optional

# Repo
[main]
Include = /data/data/com.termux/files/usr/etc/pacman.d/serverlist
EOF

pacman-key --init
pacman-key --populate
pacman -Syyu lz4 bsdtar --noconfirm

rm -rf "${HOME}/"*
[[ -d "${path}" ]] && rm -rf "${path}"

mkdir -p "${path}"
curl -fL "${url}" | lz4 -dc | bsdtar -x -C "${tmp}"

exec bash "${path}/ext"
