[options]
HoldPkg = pacman
Architecture = aarch64

Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 12

SigLevel = DatabaseRequired
LocalFileSigLevel = Optional

# Repo
[main]
Include = /data/data/com.termux/files/usr/etc/pacman.d/serverlist
